# permissions for end users to view autoscalinglisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscalinglistener-viewer-role
rules:
- apiGroups:
  - actions.summerwind.dev
  resources:
  - autoscalinglisteners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.summerwind.dev
  resources:
  - autoscalinglisteners/status
  verbs:
  - get
