# permissions for end users to view ephemeralrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeralrunner-viewer-role
rules:
- apiGroups:
  - actions.summerwind.dev
  resources:
  - ephemeralrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.summerwind.dev
  resources:
  - ephemeralrunners/status
  verbs:
  - get
