apiVersion: v1
kind: Pod
metadata:
  name: runnertest
spec:
  containers:
    - name: runner
      image: jokicnikola07/rn:latest
      command: ["/runner/run.sh"]
      volumeMounts:
        - name: runner
          mountPath: /runner
  initContainers:
    - name: setup
      image: jokicnikola07/rn:latest
      command: ["sh", "-c", "cp -r /actions-runner/* /runner/"]
      volumeMounts:
        - name: runner
          mountPath: /runner
  volumes:
    - name: runner
      emptyDir: {}
