name: CI-ARC

on:
  workflow_dispatch:
  
jobs:
  a:
    strategy:
      fail-fast: false
      matrix:
        job: [1, 2, 3]
    runs-on: example-ephemeral-runner-replica-set
    steps:
      - run: |
         printenv|sort
         # echo "Hello World!" >> $GITHUB_STEP_SUMMARY


