name: CI-ARC

on:
  workflow_dispatch:
  
jobs:
  setup-job:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install latest version of Kind
        run: |
          GO111MODULE=on go get sigs.k8s.io/kind
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH kind create cluster --name e2e-test
      - name: Cert manager setup
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
          kubectl -n cert-manager wait deploy/cert-manager-cainjector --for condition=available --timeout 90s
	  kubectl -n cert-manager wait deploy/cert-manager-webhook --for condition=available --timeout 60s
          kubectl -n cert-manager wait deploy/cert-manager --for condition=available --timeout 60s
      - name: Create release
        run: kubectl create -f release/actions-runner-controller.yaml
      - name: Create secret generic controller-manager
        run: kubectl create secret generic controller-manager -n actions-runner-system \
	     --from-literal=github_token=${secrets.GITHUB_TOKEN}
      - name: Create deployment
        run: kubectl apply -f runnerdeployment.yaml
  self-hosted-runner-job:
    needs: setup-job
    strategy:
      fail-fast: false
      matrix:
        job: [1, 2, 3]
    runs-on: example-auto-scale-runner-set
    steps:
      - run: |
         printenv|sort
         # echo "Hello World!" >> $GITHUB_STEP_SUMMARY


