name: Self Hosted Service Example
on: workflow_dispatch

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: self-hosted

    # Service containers to run with `container-job`
    services:
      custom-fail-service:
        image: avastancu/docker-container-error-generator

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Wait 10 secs
        run: sleep 10 
