name: Self Hosted Service Example
on: [push, workflow_dispatch]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: self-hosted

    # Service containers to run with `container-job`
    services:
#       custom-fail-service:
#         image: avastancu/docker-container-error-generator
#       second-custom-fail-service:
#         image: joannaakl/failing-docker:latest
       consul:
        image: public.ecr.aws/hashicorp/consul:1.11.2
        ports:
          - 8500:8500
       vault:
        image: public.ecr.aws/hashicorp/vault:1.9.3
        options: --name vault
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: myroot
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: myroot
      

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Wait 10 secs
        run: sleep 10 
