name: ARC-SIMPLE-WORKFLOW
on:
  workflow_dispatch:
jobs:
  arc-runner-job:
    strategy:
      fail-fast: false
      matrix:
        job: [1, 2, 3, 4, 5, 6, 7]
    runs-on: arc-runner-set
    steps:
      - run: echo "Hello from ARC!" >> $GITHUB_STEP_SUMMARY
