name: CI-ARC-E2E-TEST

on:
  workflow_dispatch:
  
jobs:
  setup-steps:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install latest version of Kind
        run: go install sigs.k8s.io/kind@latest
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH
          kind create cluster --name e2e-test
      - name: Helm installation
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      - name: Install ARC
        run: helm install arc --namespace "arc-systems" --create-namespace oci://ghcr.io/actions/actions-runner-controller-charts/actions-runner-controller-2 --version 0.1.0
      - name: Install runners
        run: |
          helm install "arc-runner-set" \
          --namespace "arc-runners" \
          --create-namespace \
          --set githubConfigUrl="https://github.com/AvaStancu/actions-workflows" \
          --set githubConfigSecret.github_token="${{ secrets.GITHUB_TOKEN }}" \
          oci://ghcr.io/actions/actions-runner-controller-charts/auto-scaling-runner-set --version 0.1.0
      - name: Test ARC scales pods up and down
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          go test ./test/e2e_arc -v
