name: CI-ARC-E2E-TEST

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: e2e-test
  RUNNER_VERSION: 2.301.1
  
jobs:
  setup-steps:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH
          kind create cluster --name $CLUSTER_NAME
      - name: Add env variables
        run: |
            echo "VERSION=$(echo "0.0."$GITHUB_SHA)" >> $GITHUB_ENV
            echo "IMAGE_TAG=$(echo "test-image:"$VERSION)" >> $GITHUB_ENV
      - name: Docker Build Test Image
        run: |
            echo $IMAGE_TAG
            docker build . --platform "linux/amd64,linux/arm64" --build-arg RUNNER_VERSION=$RUNNER_VERSION --build-arg VERSION=$VERSION -t $IMAGE_TAG
      - name: Load Image to Kind Cluster
        run: kind load docker-image $VERSION --name $CLUSTER_NAME
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ARC_AVA_APP_ID }}
          application_private_key: ${{ secrets.ARC_AVA_APP_PK }}
      - uses: ./.github/actions/e2e-arc-test
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          docker-image-tag: $IMAGE_TAG
