name: CI-ARC-E2E-TEST

on:
  workflow_dispatch:
  
jobs:
  setup-steps:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH
          kind create cluster --name e2e-test
      - name: Get SHA of commit that triggered the e2e workflow_dispatch
        id: commit-sha
        run: echo git rev-parse --short "$GITHUB_SHA"
      - name: Echo version tag
        run: echo ${{ steps.commit-sha.outputs.stdout }} >> $GITHUB_STEP_SUMMARY
      - name: Echo version tag
        run: echo "0.0."${{ steps.version-tag.outputs.stdout }} >> $GITHUB_STEP_SUMMARY
      - name: Docker Build Test Image
        run: docker buildx build --tag "0.0."${{ steps.version-tag.outputs.stdout }}
      - name: Load Image to Kind Cluster
        run: kind load docker-image ${{ steps.version-tag.outputs.stdout }} --name ${{ inputs.kind-cluster }}
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ARC_AVA_APP_ID }}
          application_private_key: ${{ secrets.ARC_AVA_APP_PK }}
      - uses: ./.github/actions/e2e-arc-test
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
