name: CI-ARC-E2E-TEST

on:
  workflow_dispatch:
  
jobs:
  setup-steps:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install latest version of Kind
        run: go install sigs.k8s.io/kind@latest
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH
          kind create cluster --name e2e-test
      - uses: ./.github/actions/e2e-arc-test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete Kind cluster
        run: kind delete cluster --name e2e-test
