name: Validate consul-template?

on: push

jobs:
  validate-consul-template:
    runs-on: [self-hosted]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: run consul-template validation
        run: |
          echo "we run consul-template validation here!"

    services:
      consul:
        image: public.ecr.aws/hashicorp/consul:1.11.2
