on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Greetings job
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: avastancu/composite-actions@v1
        with:
          who-to-greet: 'Mona The Oktocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      
