name: ARC-REUSABLE-WORKFLOW
on:
  workflow_dispatch:
jobs:
  some-job:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     job: [1, 2, 3]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear, grapes, melon, orange, lemon, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty]
        animal: [cat, dog, bear, penguin, mouse, horse, lion, leopard, giraffe, whale]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - run: echo "Hello World!" >> $GITHUB_STEP_SUMMARY
