name: Publish New Helm Chart to OCI

on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: 'Test scenario tags'
        required: true
        default: '0.1.0'
        type: string

permissions:
  contents: read
  packages: write

env:
  HELM_VERSION: v3.8.0

jobs:
  publish-chart:
    name: Publish Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v3.3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Publish Chart
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

          helm package charts/actions-runner-controller-2/ --version=${{ inputs.chart_version }}

          # Tag is inferred from SemVer of Chart and cannot be set manually.
          # See https://helm.sh/docs/topics/registries/#the-push-subcommand
          helm push actions-runner-controller-${{ inputs.chart_version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/actions-runner-controller-helm-chart-2

