name: reusableA
on:
  workflow_call:

concurrency: reusableA

jobs:
  triage:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v4
    - run: echo "Hello, world!"  
