name: Simple run with &

on:
  workflow_dispatch:

jobs:
  simplerun:
    runs-on: ubuntu-latest
    steps:

    - name: Run
      run: |
            echo "Tags: $TAGS"
            echo "Environment: $ENVIRONMENT"
      env:
          TAGS: ATAG
          ENVIRONMENT: TEST
          FOO: ${{ secrets.FOO1 }}
