name: Deadlock Testing
on:
  workflow_dispatch:

concurrency: foo

jobs:
  child1:
    runs-on: ubuntu-latest 
    concurrency: bar
    steps:
      - uses: actions/checkout@v3
      - name: Hello 1
        run: echo Hello, world1!
  child2:
    needs: ["child1"]
    runs-on: ubuntu-latest 
    concurrency: foo
    steps:
      - uses: actions/checkout@v3
      - name: Hello 2
        run: echo Hello, world2!

# name: Workflow with labels
# on: [workflow_dispatch]

# jobs:
#   deploy:
#     runs-on: [azure-nonprod]
#     steps:
#       - name: Run a one-line script
#         run: echo Hello, world1!
